-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 17:21:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema worktalk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema worktalk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `worktalk` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `worktalk` ;

-- -----------------------------------------------------
-- Table `worktalk`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worktalk`.`chat` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `share_code` VARCHAR(45),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  ,
  UNIQUE INDEX `share_code_UNIQUE` (`share_code` ASC)  )
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `worktalk`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worktalk`.`user` (
  `id` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `lang` ENUM('es', 'en', 'fr', 'it') NULL DEFAULT 'en',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  )
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `worktalk`.`member_of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worktalk`.`member_of` (
  `user_id` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `chat_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `last_connection` TIMESTAMP NULL DEFAULT NULL,
  `role` ENUM('user', 'admin') NULL DEFAULT 'user',
  PRIMARY KEY (`user_id`, `chat_id`),
  INDEX `fk_user_has_chat_chat1_idx` (`chat_id` ASC)  ,
  INDEX `fk_user_has_chat_user_idx` (`user_id` ASC)  ,
  CONSTRAINT `fk_user_has_chat_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `worktalk`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_chat_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `worktalk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `worktalk`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worktalk`.`message` (
  `id` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(65000) NULL DEFAULT NULL,
  `sent` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `chat_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `sender_id` INT(4) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`, `chat_id`, `sender_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  ,
  INDEX `fk_message_chat1_idx` (`chat_id` ASC)  ,
  INDEX `fk_message_user1_idx` (`sender_id` ASC)  ,
  CONSTRAINT `fk_message_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `worktalk`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `worktalk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `worktalk`.`friendship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worktalk`.`friendship` (
  `user_id_1` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `user_id_2` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `accepted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`user_id_1`, `user_id_2`),
  INDEX `fk_user_has_user_user2_idx` (`user_id_2` ASC)  ,
  INDEX `fk_user_has_user_user1_idx` (`user_id_1` ASC)  ,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`user_id_1`)
    REFERENCES `worktalk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user2`
    FOREIGN KEY (`user_id_2`)
    REFERENCES `worktalk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
