-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 17:21:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema worktalk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema worktalk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `worktalk` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `worktalk` ;

-- -----------------------------------------------------
-- Table `worktalk`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worktalk`.`chat` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `share_code` VARCHAR(45),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  ,
  UNIQUE INDEX `share_code_UNIQUE` (`share_code` ASC)  )
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `worktalk`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worktalk`.`user` (
  `id` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `lang` ENUM('es', 'en', 'fr', 'it') NULL DEFAULT 'en',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  )
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `worktalk`.`member_of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worktalk`.`member_of` (
  `user_id` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `chat_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `last_connection` TIMESTAMP NULL DEFAULT NULL,
  `role` ENUM('user', 'admin') NULL DEFAULT 'user',
  PRIMARY KEY (`user_id`, `chat_id`),
  INDEX `fk_user_has_chat_chat1_idx` (`chat_id` ASC)  ,
  INDEX `fk_user_has_chat_user_idx` (`user_id` ASC)  ,
  CONSTRAINT `fk_user_has_chat_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `worktalk`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_chat_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `worktalk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `worktalk`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worktalk`.`message` (
  `id` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(65000) NULL DEFAULT NULL,
  `sent` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `chat_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `sender_id` INT(4) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`, `chat_id`, `sender_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  ,
  INDEX `fk_message_chat1_idx` (`chat_id` ASC)  ,
  INDEX `fk_message_user1_idx` (`sender_id` ASC)  ,
  CONSTRAINT `fk_message_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `worktalk`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `worktalk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `worktalk`.`friendship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worktalk`.`friendship` (
  `user_id_1` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `user_id_2` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `accepted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`user_id_1`, `user_id_2`),
  INDEX `fk_user_has_user_user2_idx` (`user_id_2` ASC)  ,
  INDEX `fk_user_has_user_user1_idx` (`user_id_1` ASC)  ,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`user_id_1`)
    REFERENCES `worktalk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user2`
    FOREIGN KEY (`user_id_2`)
    REFERENCES `worktalk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- TEST VALUES INSERTION --
-- CHATS
INSERT INTO `worktalk`.`chat` (`name`, `share_code`) VALUES ('Big Company employees', '8283377');
INSERT INTO `worktalk`.`chat` (`name`, `share_code`) VALUES ('Testing Department chat', '1029234');

-- USERS
INSERT INTO `worktalk`.`user` (`username`, `passwd`, `email`) VALUES ('john smith', '$2y$10$1P6xpGQ./MxnhfnQ8W44P.9bABv8rKZxh17Oq9vYahUcmMrUX5nMK', 'john.smith@bigcompany.com');
INSERT INTO `worktalk`.`user` (`username`, `passwd`, `email`) VALUES ('lina watson', '$2y$10$abVvkS/Mw2Qy.FrYYp9C5OellK.hRyYJwgN89RT5vk.saZCJkRQUm', 'lina.watson@bigcompany.com');
INSERT INTO `worktalk`.`user` (`username`, `passwd`, `email`) VALUES ('brendon norris', '$2y$10$/m2NfNC5NRgMH61I9OGJVeTc5GyccfVbgEFWxobkYVam992sDICaG', 'brendon.norris@bigcompany.com');
INSERT INTO `worktalk`.`user` (`username`, `passwd`, `email`) VALUES ('daniel peckerman', '$2y$10$axtyisy/mASeOtjVeKJdZelOdWbYrO6ak3vAjgdvcoW6LQPmi62Na', 'daniel.peckerman@bigcompany.com');
INSERT INTO `worktalk`.`user` (`username`, `passwd`, `email`) VALUES ('yajaira ruderman', '$2y$10$EBSzSvGgiYd6t0k11swUUevDR6/9SlMdwRZtJFm.FW.J2modcQyXa', 'yajaira.ruderman@bigcompany.com');
INSERT INTO `worktalk`.`user` (`username`, `passwd`, `email`) VALUES ('junie luss', '$2y$10$rtLx0HQKTvT7gl7BSKSqle9fw1LkzlxZ992PgMVftiaZ0UHQgXMFi', 'junie.luss@bigcompany.com');

-- ADD USERS TO CHATS
INSERT INTO `worktalk`.`member_of` (`user_id`, `chat_id`, `last_connection`) VALUES ('30', '61', '2019-11-30 11:52:17');
UPDATE `worktalk`.`member_of` SET `role` = 'admin' WHERE (`user_id` = '0030') and (`chat_id` = '61');
INSERT INTO `worktalk`.`member_of` (`user_id`, `chat_id`, `last_connection`) VALUES ('28', '61', '2019-11-30 11:52:17');
INSERT INTO `worktalk`.`member_of` (`user_id`, `chat_id`, `last_connection`) VALUES ('29', '61', '2019-11-30 11:52:17');
INSERT INTO `worktalk`.`member_of` (`user_id`, `chat_id`, `last_connection`) VALUES ('31', '61', '2019-11-30 11:52:17');
INSERT INTO `worktalk`.`member_of` (`user_id`, `chat_id`, `last_connection`) VALUES ('32', '61', '2019-11-30 11:52:17');
INSERT INTO `worktalk`.`member_of` (`user_id`, `chat_id`, `last_connection`) VALUES ('33', '61', '2019-11-30 11:52:17');
INSERT INTO `worktalk`.`member_of` (`user_id`, `chat_id`) VALUES ('33', '62');
INSERT INTO `worktalk`.`member_of` (`user_id`, `chat_id`) VALUES ('29', '62');

-- ADD MESSAGES
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Created the chat.', '2019-11-30 11:52:17', '61', '30');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Created the chat.', '2019-11-30 11:52:17', '62', '33');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Joined the chat.', '2019-11-30 11:53:17', '61', '28');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Joined the chat.', '2019-11-30 11:53:17', '61', '29');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Joined the chat.', '2019-11-30 11:53:17', '61', '31');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Joined the chat.', '2019-11-30 11:53:17', '61', '32');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Joined the chat.', '2019-11-30 11:53:17', '61', '33');

INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Hello!', '2019-11-30 11:54:17', '61', '29');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Hello everyone', '2019-11-30 11:54:27', '61', '31');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Hello and welcome to the Big Company worktalk group. This chat was created to share general notices and to be used as a general board', '2019-11-30 11:55:07', '61', '30');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Please, John and Lina, join the Testing department chat for specific conversations about that topic. This chat is not for that', '2019-11-30 11:55:17', '61', '30');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('This is the code for the Testing Department chat: 1029234', '2019-11-30 11:55:19', '61', '30');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Ok! understood', '2019-11-30 11:57:17', '61', '30');
INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('By the way, I sent you all a friendship request to start private chats with each of you', '2019-11-30 14:39:49', '61', '30');

INSERT INTO `worktalk`.`message` (`content`, `sent`, `chat_id`, `sender_id`) VALUES ('Joined the chat.', '2019-11-30 11:57:36', '62', '33');

-- FRIENDSHIP REQUESTS
INSERT INTO `worktalk`.`friendship` (`user_id_1`, `user_id_2`) VALUES ('30', '28');
INSERT INTO `worktalk`.`friendship` (`user_id_1`, `user_id_2`) VALUES ('30', '29');
INSERT INTO `worktalk`.`friendship` (`user_id_1`, `user_id_2`) VALUES ('30', '31');
INSERT INTO `worktalk`.`friendship` (`user_id_1`, `user_id_2`) VALUES ('30', '32');
INSERT INTO `worktalk`.`friendship` (`user_id_1`, `user_id_2`) VALUES ('30', '33');
